version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: ["./bin/docker-entrypoint.prod"]
    command: ["./bin/rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - DATABASE_NAME=production.sqlite3
      - DOMAIN=https://jaggdl.dev
      - SECRET_KEY_BASE=1
      - RAILS_LOG_TO_STDOUT=1
      - RAILS_SERVE_STATIC_FILES=1
    expose:
      - "3000"
