version: '3'
services:
  jaggdl:
    build: .
    entrypoint: ["./bin/docker-entrypoint"]
    command: ["./bin/rails", "server", "-p", "4200", "-b", "0.0.0.0", "--pid", "tmp/pids/server-jaggdl.pid"]
    volumes:
      - .:/rails
    ports:
      - "4200:4200"
    environment:
      - RAILS_ENV=development
      - DATABASE_NAME=development.sqlite3
      - DOMAIN=https://jaggdl.dev
    networks:
      - app_net
    expose:
      - "4200"
    tty: true  # Add tty: true for the main service if needed

  chano:
    build: .
    entrypoint: ["./bin/docker-entrypoint"]
    command: ["./bin/rails", "server", "-p", "4201", "-b", "0.0.0.0", "--pid", "tmp/pids/server-chano.pid"]
    volumes:
      - .:/rails
    ports:
      - "4201:4201"
    environment:
      - RAILS_ENV=development
      - DATABASE_NAME=additional.sqlite3
      - DOMAIN=https://chano.dev
    networks:
      - app_net
    expose:
      - "4201"
    tty: true  # Add tty: true for the main service if needed

  tailwind:
    build: .
    entrypoint: ["./bin/docker-entrypoint"]
    command: ["./bin/rails", "tailwindcss:watch[always]"]  # Use the always argument
    volumes:
      - .:/rails
    environment:
      - RAILS_ENV=development
    networks:
      - app_net
    tty: true  # Ensure tty is true for the watch service

  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certificates:/etc/certificates
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
